### ISSUE TITLE
Fix test cooler file

### ISSUE THREAD

**Issue by flekschas** [hms-dbmi/higlass-server#3]
The file at https://s3.amazonaws.com/pkerp/public/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool does not contain necessary attributes, such as `max_zoom`. It should be replaced by `data/dixon2012-h1hesc-hindiii-allreps-filtered.1000kb.multires.cool`.

The AWS files only contains the following attrs:
- 3
- 2
- 1
- 0

while the checked in file additionally has:
- 4
- max_zoom

**Comment by mccalluc** [comment]
@flekschas : All the tests are passing now. If there some feature you think we should be testing, but aren't, please file a new bug? Thanks!
